FROM bitnami/spark:latest

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

# Set the MPLCONFIGDIR environment variable
ENV MPLCONFIGDIR /app/matplotlib_config

COPY . .

CMD ["python", "Analyse_donnees.py"]
