version: '3'
services:
  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./app:/app

  pyspark:
    build:
      context: .
      dockerfile: Dockerfile_pyspark
    container_name: pyspark
    depends_on:
      - spark
    volumes:
      - ./app:/app
    command: ["python", "Analyse_donnees.py"]
