version: '3'
services:
  spark:
    image: bitnami/spark:latest
    container_name: spark_bloc23
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./app:/app
    # command: ["tail", "-f", "/dev/null"]  # Reste en cours d'exécution pour garder le conteneur actif
